name: Build and Push Docker Images

on:
  workflow_dispatch:
    inputs:
      godot_branch:
        description: "Select the Godot branch"
        required: true
        default: "4.3"
        type: string
        options:
          - "4.3"
          - "4.4"

jobs:
  checkout:
    name: Checkout Code
    runs-on: ubuntu-latest
    outputs:
      godot_branch: ${{ github.event.inputs.godot_branch }}
    
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
    
    - name: Convert to lowercase
      run: |
        echo "GITHUB_REPO=${GITHUB_REPO@L}" >> "${GITHUB_ENV}"
  
  login:
    name: Login to GitHub Container Registry
    runs-on: ubuntu-latest
    needs: checkout
    steps:
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

  download-xcode:
    name: Download Xcode SDK
    runs-on: ubuntu-latest
    needs: checkout
    steps:
    - name: Download Xcode SDK
      run: |
        echo "Downloading Xcode SDK..."
        curl -L "https://www.dropbox.com/scl/fi/hhfj8cpobavpz98gz1jyf/Xcode_16.2.xip?rlkey=k1xjrugbfwhtjs9p0h5ewxyid&st=k89g5fn6&raw=1" -o Xcode_16.2.xip
        echo "Xcode installer downloaded successfully."

  build-base:
    name: Build and Push Base Image
    runs-on: ubuntu-latest
    needs: [checkout, login]
    steps:
    - name: Build and Push Base Image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: ghcr.io/${{ env.GITHUB_REPO }}/godot-fedora:${{ needs.checkout.outputs.godot_branch }}
        file: Dockerfile.base

  build-linux:
    name: Build and Push Linux Image
    runs-on: ubuntu-latest
    needs: [checkout, login]
    steps:
    - name: Build and Push Linux Image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: ghcr.io/${{ env.GITHUB_REPO }}/godot-linux:${{ needs.checkout.outputs.godot_branch }}
        file: Dockerfile.linux
        build-args: |
          img_version=${{ needs.checkout.outputs.godot_branch }}
          registry_base_path=ghcr.io/${{ env.GITHUB_REPO }}

  build-windows:
    name: Build and Push Windows Image
    runs-on: ubuntu-latest
    needs: [checkout, login]
    steps:
    - name: Build and Push Windows Image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: ghcr.io/${{ env.GITHUB_REPO }}/godot-windows:${{ needs.checkout.outputs.godot_branch }}
        file: Dockerfile.windows
        build-args: |
          img_version=${{ needs.checkout.outputs.godot_branch }}
          registry_base_path=ghcr.io/${{ env.GITHUB_REPO }}

  build-web:
    name: Build and Push Web Image
    runs-on: ubuntu-latest
    needs: [checkout, login]
    steps:
    - name: Build and Push Web Image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: ghcr.io/${{ env.GITHUB_REPO }}/godot-web:${{ needs.checkout.outputs.godot_branch }}
        file: Dockerfile.web
        build-args: |
          img_version=${{ needs.checkout.outputs.godot_branch }}
          registry_base_path=ghcr.io/${{ env.GITHUB_REPO }}

  build-android:
    name: Build and Push Android Image
    runs-on: ubuntu-latest
    needs: [checkout, login]
    steps:
    - name: Build and Push Android Image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: ghcr.io/${{ env.GITHUB_REPO }}/godot-android:${{ needs.checkout.outputs.godot_branch }}
        file: Dockerfile.android
        build-args: |
          img_version=${{ needs.checkout.outputs.godot_branch }}
          registry_base_path=ghcr.io/${{ env.GITHUB_REPO }}

  build-xcode:
    name: Build and Push Xcode Image
    runs-on: ubuntu-latest
    needs: [checkout, login, download-xcode]
    steps:
    - name: Build and Push Xcode Image
      run: |
        echo "Building OSX and iOS SDK packages..."
        docker build \
          --build-arg img_version=${{ needs.checkout.outputs.godot_branch }} \
          -v "$(pwd)/files:/root/files:z" \
          -t ghcr.io/${{ env.GITHUB_REPO }}/godot-xcode:${{ needs.checkout.outputs.godot_branch }} \
          -f Dockerfile.xcode
        docker push ghcr.io/${{ env.GITHUB_REPO }}/godot-xcode:${{ needs.checkout.outputs.godot_branch }}

  build-osx:
    name: Build and Push OSX Image
    runs-on: ubuntu-latest
    needs: [checkout, login]
    steps:
    - name: Build and Push OSX Image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: ghcr.io/${{ env.GITHUB_REPO }}/godot-osx:${{ needs.checkout.outputs.godot_branch }}
        file: Dockerfile.osx
        build-args: |
          img_version=${{ needs.checkout.outputs.godot_branch }}
          registry_base_path=ghcr.io/${{ env.GITHUB_REPO }}

  build-ios:
    name: Build and Push iOS Image
    runs-on: ubuntu-latest
    needs: [checkout, login]
    steps:
    - name: Build and Push iOS Image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: ghcr.io/${{ env.GITHUB_REPO }}/godot-ios:${{ needs.checkout.outputs.godot_branch }}
        file: Dockerfile.ios
        build-args: |
          img_version=${{ needs.checkout.outputs.godot_branch }}
          registry_base_path=ghcr.io/${{ env.GITHUB_REPO }}
