name: Build and Push Docker Images

on:
  workflow_dispatch:
    inputs:
      godot_branch:
        description: "Select the Godot branch"
        required: true
        default: "4.3"
        type: string
        options:
          - "4.3"
          - "4.4"

env:
  REPO: ughuuu/build-containers

jobs:
  build-base:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: ghcr.io/${{ env.REPO }}/godot-fedora:${{ inputs.godot_branch }}
        file: Dockerfile.base

  build-linux:
    needs: [build-base]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: ghcr.io/${{ env.REPO }}/godot-linux:${{ inputs.godot_branch }}
        file: Dockerfile.linux
        build-args: |
          img_version=${{ inputs.godot_branch }}
          registry_base_path=ghcr.io/${{ env.REPO }}

  build-windows:
    runs-on: ubuntu-latest
    needs: [build-base]
    steps:
    - uses: actions/checkout@v3
    - uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: ghcr.io/${{ env.REPO }}/godot-windows:${{ inputs.godot_branch }}
        file: Dockerfile.windows
        build-args: |
          img_version=${{ inputs.godot_branch }}
          registry_base_path=ghcr.io/${{ env.REPO }}

  build-web:
    runs-on: ubuntu-latest
    needs: [build-base]
    steps:
    - uses: actions/checkout@v3
    - uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: ghcr.io/${{ env.REPO }}/godot-web:${{ inputs.godot_branch }}
        file: Dockerfile.web
        build-args: |
          img_version=${{ inputs.godot_branch }}
          registry_base_path=ghcr.io/${{ env.REPO }}

  build-android:
    runs-on: ubuntu-latest
    needs: [build-base]
    steps:
    - uses: actions/checkout@v3
    - uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: ghcr.io/${{ env.REPO }}/godot-android:${{ inputs.godot_branch }}
        file: Dockerfile.android
        build-args: |
          img_version=${{ inputs.godot_branch }}
          registry_base_path=ghcr.io/${{ env.REPO }}

  build-xcode:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Download Xcode SDK
      run: |
        echo "Downloading Xcode SDK..."
        mkdir files
        curl -L "https://www.dropbox.com/scl/fi/hhfj8cpobavpz98gz1jyf/Xcode_16.2.xip?rlkey=k1xjrugbfwhtjs9p0h5ewxyid&st=k89g5fn6&raw=1" -o files/Xcode_16.2.xip
        echo "Xcode installer downloaded successfully."
    - uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: ghcr.io/${{ env.REPO }}/godot-xcode:${{ inputs.godot_branch }}
        file: Dockerfile.xcode
        build-args: |
          img_version=${{ inputs.godot_branch }}
          registry_base_path=ghcr.io/${{ env.REPO }}

  build-osx:
    runs-on: ubuntu-latest
    needs: [build-xcode]
    steps:
    - uses: actions/checkout@v3
    - uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: ghcr.io/${{ env.REPO }}/godot-osx:${{ inputs.godot_branch }}
        file: Dockerfile.osx
        build-args: |
          img_version=${{ inputs.godot_branch }}
          registry_base_path=ghcr.io/${{ env.REPO }}

  build-ios:
    runs-on: ubuntu-latest
    needs: [build-xcode]
    steps:
    - uses: actions/checkout@v3
    - uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: ghcr.io/${{ env.REPO }}/godot-ios:${{ inputs.godot_branch }}
        file: Dockerfile.ios
        build-args: |
          img_version=${{ inputs.godot_branch }}
          registry_base_path=ghcr.io/${{ env.REPO }}
